// File generated by FlutterFire CLI.
// This file is used to configure Firebase for your Flutter app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu4ZBX9XahQKmcWAv5yHJVcZwk2TCWz-8',
    appId: '1:445118184031:web:130b973ba41b5db99c39ea',
    messagingSenderId: '445118184031',
    projectId: 'aicoach-6950b',
    authDomain: 'aicoach-6950b.firebaseapp.com',
    storageBucket: 'aicoach-6950b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO_y0ij-sCsFZW39zkRV_vOez3pmpBfIs',
    appId: '1:445118184031:android:40b0b1cb9844ab2d9c39ea',
    messagingSenderId: '445118184031',
    projectId: 'aicoach-6950b',
    storageBucket: 'aicoach-6950b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB-6cShol_6nG8rHdbSxzyhw_qkPLeMto',
    appId: '1:445118184031:ios:e6afc41b5cf4c1699c39ea',
    messagingSenderId: '445118184031',
    projectId: 'aicoach-6950b',
    storageBucket: 'aicoach-6950b.firebasestorage.app',
    iosBundleId: 'com.example.argumentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB-6cShol_6nG8rHdbSxzyhw_qkPLeMto',
    appId: '1:445118184031:ios:e6afc41b5cf4c1699c39ea',
    messagingSenderId: '445118184031',
    projectId: 'aicoach-6950b',
    storageBucket: 'aicoach-6950b.firebasestorage.app',
    iosBundleId: 'com.example.argumentor',
  );

}